---
- name: Make connections to hosts more secure.
  hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    sshd_config_path: /etc/ssh/sshd_config

  tasks:

  - name: Disable PasswordAuthentication
    ansible.builtin.lineinfile:
      path: "{{ sshd_config_path }}"
      regexp: "^#PasswordAuthentication"
      line: "PasswordAuthentication no"

  - name: Disable PermitEmptyPasswords
    ansible.builtin.lineinfile:
      path: "{{ sshd_config_path }}"
      regexp: "^#PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"

  - name: Disable PermitRootLogin
    ansible.builtin.lineinfile:
      path: "{{ sshd_config_path }}"
      regexp: "^#PermitRootLogin"
      line: "PermitRootLogin no"

  - name: Restart sshd.service
    ansible.builtin.service:
      name: sshd.service
      state: restarted

