---
- name: First system preparing
  hosts: all
  gather_facts: no
  become: no
  vars: 
    ssh_key_filename: ssh_roman_admin_key
    ssh_key_location_path: ~/git/it_study/ansible/admin/ssh
    sshd_config_file: /etc/ssh/sshd_config
    local_user: roman
  
  tasks:
  - name: generate SSH key "{{ ssh_key_filename }}"
    user:
      name: "{{ local_user  }}"
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_bits: 4096
      ssh_key_file: "{{ ssh_key_location_path }}/{{ ssh_key_filename }}"
      force: no
    delegate_to: localhost
    run_once: yes

  #- name: debug
  #  debug:
  #    msg: "{{ lookup('file', ssh_key_location_path+'/'+ssh_key_filename+'.pub') }}"

  - name: copy SSH key to remote hosts
    ansible.builtin.authorized_key:
      key: "{{ lookup('file', ssh_key_location_path+'/'+ssh_key_filename+'.pub' )}}"
      state: present
      user: "{{ ansible_user  }}"
  
  - name: disable SSH password connection
    become: yes 
    become_user: root 
    become_method: sudo
    become_flags: '-s /bin/bash' 
    ansible.builtin.lineinfile:
      path: "{{ sshd_config_file  }}"
      regexp: "^#PasswordAuthentication"
      line: "PasswordAuthetication no"
